source 'https://rubygems.org'

gem 'rails'

gem 'bootstrap-sass'
gem 'coffee-rails'
gem 'haml'
gem 'inherited_resources'
gem 'jquery-rails'
gem 'pg'
gem 'sass-rails'
gem 'simple_form'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry',              require: false
  gem 'spring'
end

group :test do
  gem 'factory_girl'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end
